#!/usr/bin/env python3
"""Write computed Site external evidence state.

This keeps remaining evidence tracking repository-managed instead of manual.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "docs" / "SITE_EXTERNAL_EVIDENCE_STATE.json"
OUT_MD = ROOT / "docs" / "SITE_EXTERNAL_EVIDENCE_STATE.md"

CHECKS = [
    {
        "id": "tt_bundle_present",
        "label": "TT propagated bundle present",
        "path": "data/tt/transition-element-propagation-bundle.manifest.json",
    },
    {
        "id": "tt_status_markdown_present",
        "label": "TT status markdown present",
        "path": "docs/SITE_TT_CODE_REPRESENTATION_STATUS.md",
    },
    {
        "id": "tt_status_json_present",
        "label": "TT status JSON present",
        "path": "docs/SITE_TT_CODE_REPRESENTATION_STATUS.json",
    },
    {
        "id": "governance_observatory_markdown_present",
        "label": "Governance Observatory status markdown present",
        "path": "docs/SITE_GOVERNANCE_OBSERVATORY_STATUS.md",
    },
    {
        "id": "governance_observatory_json_present",
        "label": "Governance Observatory status JSON present",
        "path": "docs/SITE_GOVERNANCE_OBSERVATORY_STATUS.json",
    },
]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def check_record(item: dict[str, str]) -> dict[str, object]:
    path = ROOT / item["path"]
    text = read_text(path)
    pending = "PENDING" in text or "pending" in text
    return {
        "id": item["id"],
        "label": item["label"],
        "path": item["path"],
        "exists": path.exists(),
        "pending_text_present": pending,
        "status": "present" if path.exists() else "missing",
    }


def build_state() -> dict[str, object]:
    records = [check_record(item) for item in CHECKS]
    required_present = all(record["exists"] for record in records)
    bundle_present = next(record for record in records if record["id"] == "tt_bundle_present")["exists"]
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "repository": "StegVerse-Labs/Site",
        "state": "pending_external_evidence" if not required_present or not bundle_present else "external_evidence_present",
        "local_build_state": "repository_managed",
        "records": records,
        "next_action": "Repository workflows continue checking until external evidence is present.",
        "non_claim": "This state file does not grant execution authority or change source-repository authority.",
    }


def render_markdown(state: dict[str, object]) -> str:
    lines = [
        "# Site External Evidence State",
        "",
        "## Status",
        "",
        "```text",
        f"state: {state['state']}",
        f"generated_at: {state['generated_at']}",
        f"local_build_state: {state['local_build_state']}",
        "```",
        "",
        "## Evidence Records",
        "",
        "| ID | Path | Exists | Pending Text Present |",
        "|---|---|---:|---:|",
    ]
    for record in state["records"]:  # type: ignore[index]
        lines.append(
            f"| {record['id']} | `{record['path']}` | {str(record['exists']).lower()} | {str(record['pending_text_present']).lower()} |"
        )
    lines.extend([
        "",
        "## Boundary",
        "",
        "This file is generated by repository workflow. It does not grant execution authority or change source-repository authority.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    state = build_state()
    OUT_JSON.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
    OUT_MD.write_text(render_markdown(state), encoding="utf-8")
    print(json.dumps({"status": "PASS", "state": state["state"]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
